# 发行源码 | Release the source code

name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Create release
      # REF https://github.com/marketplace/actions/release-please-action
      - name: Create release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

          ## A GitHub secret token, the action defaults to using the special secrets.GITHUB_TOKEN
          ## REF https://github.com/marketplace/actions/release-please-action#github-credentials
          token: ${{ secrets.PAT_ACTIONS }}

          ## branch to open pull release PR against (detected by default)
          default-branch: main

          ## Should breaking changes before 1.0.0 produce minor bumps? Default false
          bump-minor-pre-major: false

          ## Should feat changes before 1.0.0 produce patch bumps instead of minor bumps? Default false
          bump-patch-for-minor-pre-major: false

          ## If set, create releases that are pre-major or pre-release version marked as pre-release on GitHub. Defaults false
          prerelease: true

          ## header used within the release PR body, defaults to using :robot: I have created a release *beep* *boop*
          pull-request-header: ":robot: A new release will be created"

          ## A JSON formatted String containing to override the outputted changelog sections
          changelog-types: |-
            [
                {
                    "type": "build",
                    "section": "Build System",
                    "hidden": false
                },
                {
                    "type": "chore",
                    "section": "Miscellaneous",
                    "hidden": false
                },
                {
                    "type": "ci",
                    "section": "Continuous Integration",
                    "hidden": false
                },
                {
                    "type": "docs",
                    "section": "Documentation"
                },
                {
                    "type": "feat",
                    "section": "Features",
                    "hidden": false
                },
                {
                    "type": "fix",
                    "section": "Bug Fixes",
                    "hidden": false
                },
                {
                    "type": "perf",
                    "section": "Performance Improvements"
                },
                {
                    "type": "refactor",
                    "section": "Code Refactoring",
                    "hidden": false
                },
                {
                    "type": "revert",
                    "section": "Reverts"
                },
                {
                    "type": "style",
                    "section": "Styles",
                    "hidden": false
                },
                {
                    "type": "test",
                    "section": "Tests",
                    "hidden": false
                },
                {
                    "type": "",
                    "section": "Other Changes",
                    "hidden": false
                }
            ]
